### ISSUE TITLE
add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'

### ISSUE THREAD

**Issue by Sakura-nee** [ddPn08/kohya-sd-scripts-webui#4]
Failed to load scripts.tabs.training.fine_tune
add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'
Failed to load scripts.tabs.training.train_db
add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'
Failed to load scripts.tabs.training.train_network
add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'
Failed to load scripts.tabs.training.train_textual_inversion
add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'
Running on local URL:  http://127.0.0.1:7860

**Comment by ddPn08** [comment]
Fixed in a commit some time ago.
